--TABELLEN LÖSCHEN
DROP TABLE BILD CASCADE CONSTRAINTS;
DROP TABLE TOURIATTRAKTION CASCADE CONSTRAINTS;
DROP TABLE ATTRAKTIONINFO CASCADE CONSTRAINTS;
DROP TABLE BESITZT CASCADE CONSTRAINTS;
DROP TABLE AUSSTATTUNG CASCADE CONSTRAINTS;
DROP TABLE BUCHUNG CASCADE CONSTRAINTS;
DROP TABLE FERIENWOHNUNG CASCADE CONSTRAINTS;
DROP TABLE KUNDEN CASCADE CONSTRAINTS;
DROP TABLE LAND CASCADE CONSTRAINTS;

--Tabellen erstellen
CREATE TABLE LAND
(
Land_Name varchar(20) NOT NULL,
CONSTRAINT pk_Land PRIMARY KEY(Land_Name)
);

CREATE TABLE KUNDEN
(
KdNr NUMBER GENERATED ALWAYS AS IDENTITY,
K_Name varchar(20) NOT NULL,
Vorname varchar (20) NOT NULL,
Land_Name varchar(20) NOT NULL,
PLZ INTEGER NOT NULL,
Ort varchar(20) NOT NULL,
Strasse varchar(20) NOT NULL,
Email varchar(50) NOT NULL,
BIC varchar(10) NOT NULL,
IBAN varchar(22) NOT NULL,
Benutzername varchar(20) NOT NULL,
Passwort varchar(20) NOT NULL,
CONSTRAINT pk_Kunden PRIMARY KEY(KdNr),
CONSTRAINT fk_Land_Name FOREIGN KEY(Land_Name) REFERENCES Land(Land_Name) ON DELETE CASCADE
);

CREATE TABLE FERIENWOHNUNG
( 
Wohnung_Name varchar(60) NOT NULL,
Groesse NUMBER NOT NULL,
Preis NUMBER NOT NULL,
AnzZimmer NUMBER NOT NULL,
Land_Name varchar(20) NOT NULL,
CONSTRAINT pk_Ferienwohnung PRIMARY KEY(Wohnung_Name),
CONSTRAINT fk_Land_Name_Ferienwohnung FOREIGN KEY(Land_Name) REFERENCES Land(Land_Name) ON DELETE CASCADE
);

CREATE TABLE BUCHUNG
(
BuchungsNr NUMBER GENERATED ALWAYS AS IDENTITY,
Datum DATE NOT NULL,
Bewertung NUMBER(1) CHECK(Bewertung >0 AND Bewertung <6),
Zeitraum_von DATE NOT NULL,
Zeitraum_bis DATE NOT NULL,
RechnungsNr NUMBER,
Zahlungseingang DATE,
KdNr NUMBER NOT NULL,
Wohnung_Name varchar(60) NOT NULL,
CONSTRAINT ZeitraumCheck CHECK(Zeitraum_bis >= Zeitraum_von +3),
CONSTRAINT ZahlungseingangCheck CHECK(Zahlungseingang < Zeitraum_von),
CONSTRAINT pk_BUCHUNG PRIMARY KEY(BuchungsNr),
CONSTRAINT fk_KdNr FOREIGN KEY(KdNr) REFERENCES KUNDEN (KdNr),
CONSTRAINT fk_Wohnung_Name FOREIGN KEY(Wohnung_Name) REFERENCES FERIENWOHNUNG(Wohnung_Name)
);

CREATE TABLE AUSSTATTUNG
(
Bezeichnung varchar(60) NOT NULL,
Beschreibung varchar(255),
CONSTRAINT pk_AUSSTATTUNG PRIMARY KEY(Bezeichnung)
);

CREATE TABLE BESITZT
(
Wohnung_Name varchar(60) NOT NULL,
Bezeichnung varchar(60) NOT NULL,
CONSTRAINT pk_BESITZT PRIMARY KEY(Bezeichnung, Wohnung_Name),
CONSTRAINT fk_Wohnung_Name_besitzt FOREIGN KEY(Wohnung_Name) REFERENCES FERIENWOHNUNG(Wohnung_Name) ON DELETE CASCADE,
CONSTRAINT fk_Ausstattung FOREIGN KEY(Bezeichnung) REFERENCES AUSSTATTUNG(Bezeichnung) ON DELETE CASCADE
);

CREATE TABLE TOURIATTRAKTION
(
Beschreibung varchar(255) NOT NULL,
TA_Name varchar(60) NOT NULL,
CONSTRAINT pk_TOURIATTRAKTION PRIMARY KEY(TA_Name)
);

CREATE TABLE ATTRAKTIONINFO
(
Entfernung NUMBER NOT NULL,
Wohnung_Name varchar(60) NOT NULL,
TA_Name varchar(60) NOT NULL,
CONSTRAINT pk_ATTRAKTIONINFO PRIMARY KEY(TA_Name, Wohnung_Name),
CONSTRAINT fk_Wohnung_Name_ATTRAKTIONINFO FOREIGN KEY(Wohnung_Name) REFERENCES FERIENWOHNUNG(Wohnung_Name) ON DELETE CASCADE,
CONSTRAINT fk_TA_Name_ATTRAKTIONINFO FOREIGN KEY(TA_Name) REFERENCES TOURIATTRAKTION(TA_Name) ON DELETE CASCADE
);

CREATE TABLE BILD
(
Bezeichnung varchar(60) NOT NULL,
Groesse NUMBER NOT NULL CHECK(Groesse < 7),
Datentyp varchar(10) NOT NULL,
Wohnung_Name varchar(60) NOT NULL,
CONSTRAINT pk_BILD PRIMARY KEY(Bezeichnung)
);

--ZUGRIFFSBERECHTIGUNG
GRANT SELECT ON FERIENWOHNUNG TO DBSYS60;
GRANT SELECT ON TOURIATTRAKTION TO DBSYS60;
GRANT SELECT ON BILD TO DBSYS60;
GRANT SELECT ON AUSSTATTUNG TO DBSYS60;
GRANT SELECT, INSERT ON BUCHUNG TO DBSYS60;
GRANT SELECT ON LAND TO DBSYS60;
GRANT SELECT, INSERT ON KUNDEN TO DBSYS60;
GRANT SELECT ON ATTRAKTIONINFO TO DBSYS60;
GRANT SELECT ON BESITZT TO DBSYS60;

COMMIT;